# Generated by Django 5.2.4 on 2025-07-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=100)),
                ("desc", models.CharField(max_length=320)),
                ("pub_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
