# Generated by Django 5.2.4 on 2025-07-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pub_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
