# Generated by Django 5.2.4 on 2025-07-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_product_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="", upload_to="shop/images"),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="pub_date",
            field=models.DateField(),
        ),
    ]
