# Generated by Django 5.2.4 on 2025-07-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=10)),
                ("payment_method", models.CharField(max_length=20)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
