# Generated by Django 5.2.4 on 2025-07-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_order_items_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="items_json",
            field=models.JSONField(),
        ),
    ]
