# Generated by Django 5.2.4 on 2025-07-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_orderupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount",
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
