# Generated by Django 5.2.4 on 2025-07-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_order_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
