# Generated by Django 5.2.4 on 2025-07-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_alter_order_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="amount",
        ),
        migrations.AddField(
            model_name="order",
            name="mount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
