# Generated by Django 5.2.4 on 2025-07-18 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_remove_order_amount_order_mount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="mount",
            new_name="amount",
        ),
    ]
