# Generated by Django 5.2.4 on 2025-07-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_rename_mount_order_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="cod", max_length=50),
        ),
    ]
