# Generated by Django 5.2.4 on 2025-07-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_order_paid_order_payment_id_order_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="paid",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="razorpay_order_id",
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(max_length=20),
        ),
    ]
